### ISSUE TITLE
Issue with some textures that are close to the size limit/contain few 4-pixel strings

### ISSUE THREAD

**Issue by Descender1032** [arbruijn/PatchPig#1]
Hey,

The tool returns an unhandled exception: 

System.Exception: Image cannot compress efficiently.
in LibDescent.Data.RLEEncoder.EncodeImage(Int32 width, Int32 height, Byte[] buffer, Boolean& big)
in PatchPig.PatchPig.Run(String[] args_)
in PatchPig.PatchPig.Main(String[] args_)

This happens even for bitmaps which are unaltered after exporting from descent.pig, including but not limited to rock073.bmp, rock149.bmp, rock150.bmp.

One common trait that these files share is that they are close to (I'm guessing) the max size, which is 4096 bytes due to large number of individual colors contained, and few "4-and-more consecutive pixel in the same color horizontally" sequences contained. But instead of the file just being skipped for being too large, this unhandled exception appears. 

I was able to overcome the issue in rock073.bmp by manually increasing the number of four pixel sequences of the same color, though it took over a dozen instances of that to succeed.

Attaching some offending BMP files, so you can have something to test with.
[rock bmps.zip](https://github.com/arbruijn/PatchPig/files/10045680/rock.bmps.zip)

**Comment by arbruijn** [comment]
Fixed in version 0.92.
